"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "hi" | "pa";
const copy = {
  en: { excludedCities: "cities are not ranked because no station there has reported recently — not because the air is clean.", unattributedStations: "reporting stations are not shown because their names carry no city to group them under.", rankingsTitle: "Worst air right now", rankingsIntro: "Indian cities ranked by their most polluted reporting station. Each figure is a measurement from a named station, with the time it was taken.", rankingsEmpty: "No city has a reading recent enough to rank. This means the ingestion job has not run, not that the air is clean.", rankingsUnavailable: "The station read service did not respond. VAAYU will not show a ranking it could not compute.", rankedFrom: "Ranked from stations reporting within the last 6 hours, by each city’s worst station.", noMeasurement: "No measurement here. VAAYU’s 1 km surface currently covers Delhi-NCR, and this location has no monitoring station feeding it.", nearestIs: "Nearest measurement is", away: "away", measuredAtStation: "Measured at station", measuredLabel: "Measured", notReported: "This station has not reported recently. Shown with its real age.", noData: "No data", oneStation: "1 station", worstOf: "worst of", stationsWord: "stations", myAir: "My Air", report: "Report", rankings: "Rankings", console: "Console", loading: "Loading…", search: "Search city or location…", locate: "Locate Me", live: "Live data", reference: "Reference data", unavailable: "Source unavailable", reportTitle: "Community Observation Intake", reportHeading: "See something that affects the air?", reportDescription: "Report a local observation to help VAAYU understand conditions beyond sparse monitoring stations.", limitation: "Important scientific limitation", limitationText: "Photographic classification produces a rough AQI band, never a PM2.5 concentration.", addPhoto: "Add an atmospheric photograph", submit: "Submit Observation", locating: "Acquiring location…", analyzing: "Analyzing observation…", privacy: "Privacy notice", regions: "Region", coverage: "India-ready bbox-based intelligence · Multi-region demonstration", categories: ["Good", "Moderate", "Unhealthy for Sensitive Groups", "Unhealthy", "Very Unhealthy", "Hazardous"] },
  hi: { excludedCities: "शहर रैंक नहीं हुए क्योंकि वहाँ किसी स्टेशन ने हाल में रिपोर्ट नहीं की — इसलिए नहीं कि हवा साफ़ है।", unattributedStations: "स्टेशन नहीं दिखाए गए क्योंकि उनके नाम में शहर नहीं है।", rankingsTitle: "अभी सबसे खराब हवा", rankingsIntro: "भारतीय शहरों की रैंकिंग, उनके सबसे प्रदूषित स्टेशन के आधार पर।", rankingsEmpty: "किसी शहर का डेटा रैंक करने योग्य नया नहीं है। इसका अर्थ है कि डेटा आया नहीं, न कि हवा साफ़ है।", rankingsUnavailable: "स्टेशन सेवा ने जवाब नहीं दिया।", rankedFrom: "पिछले 6 घंटों में रिपोर्ट करने वाले स्टेशनों से।", noMeasurement: "यहाँ कोई माप नहीं। VAAYU की 1 किमी सतह अभी दिल्ली-NCR को कवर करती है।", nearestIs: "नज़दीकी माप", away: "दूर", measuredAtStation: "स्टेशन पर मापा गया", measuredLabel: "मापा गया", notReported: "यह स्टेशन हाल में रिपोर्ट नहीं कर रहा।", noData: "डेटा नहीं", oneStation: "1 स्टेशन", worstOf: "सबसे खराब, कुल", stationsWord: "स्टेशन", myAir: "मेरी हवा", report: "रिपोर्ट", rankings: "रैंकिंग", console: "कंसोल", loading: "लोड हो रहा है…", search: "शहर या स्थान खोजें…", locate: "मेरा स्थान", live: "लाइव डेटा", reference: "संदर्भ डेटा", unavailable: "स्रोत उपलब्ध नहीं", reportTitle: "सामुदायिक अवलोकन", reportHeading: "हवा को प्रभावित करने वाली कोई चीज़ दिखी?", reportDescription: "स्थानीय अवलोकन रिपोर्ट करें ताकि VAAYU विरल निगरानी केंद्रों से आगे की स्थितियों को समझ सके।", limitation: "महत्वपूर्ण वैज्ञानिक सीमा", limitationText: "फोटो वर्गीकरण केवल एक अनुमानित AQI श्रेणी देता है, PM2.5 सांद्रता नहीं।", addPhoto: "वायुमंडलीय फ़ोटो जोड़ें", submit: "अवलोकन भेजें", locating: "स्थान प्राप्त हो रहा है…", analyzing: "अवलोकन का विश्लेषण…", privacy: "गोपनीयता सूचना", regions: "क्षेत्र", coverage: "भारत-तैयार bbox आधारित बुद्धिमत्ता · बहु-क्षेत्र प्रदर्शन", categories: ["अच्छा", "मध्यम", "संवेदनशील लोगों के लिए अस्वास्थ्यकर", "अस्वास्थ्यकर", "बहुत अस्वास्थ्यकर", "खतरनाक"] },
  pa: { excludedCities: "ਸ਼ਹਿਰ ਦਰਜਾਬੰਦ ਨਹੀਂ ਹੋਈ ਕਿਉਂਕਿ ਉੱਥੇ ਕਿਸੇ ਸਟੇਸ਼ਨ ਨੇ ਹਾਲ ਹੀ ਰਿਪੋਰਟ ਨਹੀਂ ਕੀ।", unattributedStations: "ਸਟੇਸ਼ਨ ਨਹੀਂ ਦਿਖਾਏ ਗਏ ਕਿਉਂਕਿ ਉਨ੍ਹਾਂ ਦੇ ਨਾਮ ਵਿੱਚ ਸ਼ਹਿਰ ਨਹੀਂ।", rankingsTitle: "ਹੁਣ ਸਭ ਤੋਂ ਮਾੜੀ ਹਵਾ", rankingsIntro: "ਭਾਰਤੀ ਸ਼ਹਿਰਾਂ ਦੀ ਦਰਜਾਬੰਦੀ।", rankingsEmpty: "ਕਿਸੇ ਸ਼ਹਿਰ ਦਾ ਡਾਟਾ ਨਵਾਂ ਨਹੀਂ ਹੈ।", rankingsUnavailable: "ਸਟੇਸ਼ਨ ਸੇਵਾ ਨੇ ਜਵਾਬ ਨਹੀਂ ਦਿੱਤਾ।", rankedFrom: "ਪਿਛਲੇ 6 ਘੰਟਿਆਂ ਦੇ ਸਟੇਸ਼ਨਾਂ ਤੋ।", noMeasurement: "ਇਥੇ ਕੋਈ ਮਾਪ ਨਹੀਂ।", nearestIs: "ਨੇੜੇ ਦੀ ਮਾਪ", away: "ਦੂਰ", measuredAtStation: "ਸਟੇਸ਼ਨ ਤੇ ਮਿਣਿਆ", measuredLabel: "ਮਿਣਿਆ", notReported: "ਇਹ ਸਟੇਸ਼ਨ ਹਾਲ ਹੀ ਰਿਪੋਰਟ ਨਹੀਂ ਕਰ ਰਿਹਾ।", noData: "ਡਾਟਾ ਨਹੀਂ", oneStation: "1 ਸਟੇਸ਼ਨ", worstOf: "ਸਭ ਤੋਂ ਮਾੜਾ, ਕੁੱਲ", stationsWord: "ਸਟੇਸ਼ਨ", myAir: "ਮੇਰੀ ਹਵਾ", report: "ਰਿਪੋਰਟ", rankings: "ਦਰਜਾਬੰਦੀ", console: "ਕੰਸੋਲ", loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…", search: "ਸ਼ਹਿਰ ਜਾਂ ਥਾਂ ਲੱਭੋ…", locate: "ਮੇਰਾ ਟਿਕਾਣਾ", live: "ਲਾਈਵ ਡਾਟਾ", reference: "ਹਵਾਲਾ ਡਾਟਾ", unavailable: "ਸਰੋਤ ਉਪਲਬਧ ਨਹੀਂ", reportTitle: "ਭਾਈਚਾਰਕ ਨਿਰੀਖਣ", reportHeading: "ਹਵਾ ਨੂੰ ਪ੍ਰਭਾਵਿਤ ਕਰਨ ਵਾਲੀ ਕੋਈ ਚੀਜ਼ ਵੇਖੀ?", reportDescription: "ਸਥਾਨਕ ਨਿਰੀਖਣ ਦੀ ਰਿਪੋਰਟ ਕਰੋ ਤਾਂ ਜੋ VAAYU ਘੱਟ ਨਿਗਰਾਨੀ ਕੇਂਦਰਾਂ ਤੋਂ ਪਰੇ ਹਾਲਾਤ ਸਮਝ ਸਕੇ।", limitation: "ਮਹੱਤਵਪੂਰਨ ਵਿਗਿਆਨਕ ਸੀਮਾ", limitationText: "ਫੋਟੋ ਵਰਗੀਕਰਨ ਸਿਰਫ਼ ਇੱਕ ਅੰਦਾਜ਼ਨ AQI ਪੱਧਰ ਦਿੰਦਾ ਹੈ, PM2.5 ਸੰਘਣਤਾ ਨਹੀਂ।", addPhoto: "ਵਾਯੂਮੰਡਲੀ ਫੋਟੋ ਜੋੜੋ", submit: "ਨਿਰੀਖਣ ਭੇਜੋ", locating: "ਟਿਕਾਣਾ ਪ੍ਰਾਪਤ ਹੋ ਰਿਹਾ ਹੈ…", analyzing: "ਨਿਰੀਖਣ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ…", privacy: "ਗੋਪਨੀਯਤਾ ਸੂਚਨਾ", regions: "ਖੇਤਰ", coverage: "ਭਾਰਤ-ਤਿਆਰ bbox ਅਧਾਰਿਤ ਬੁੱਧੀ · ਬਹੁ-ਖੇਤਰ ਪ੍ਰਦਰਸ਼ਨ", categories: ["ਚੰਗਾ", "ਦਰਮਿਆਨਾ", "ਸੰਵੇਦਨਸ਼ੀਲ ਲੋਕਾਂ ਲਈ ਅਸਿਹਤਮੰਦ", "ਅਸਿਹਤਮੰਦ", "ਬਹੁਤ ਅਸਿਹਤਮੰਦ", "ਖਤਰਨਾਕ"] },
} as const;
type Copy = { [Key in keyof typeof copy.en]: Key extends "categories" ? readonly string[] : string };
const I18n = createContext<{ language: Language; setLanguage: (language: Language) => void; t: Copy }>({ language: "en", setLanguage: () => {}, t: copy.en });
export function CitizenI18nProvider({ children }: { children: React.ReactNode }) { const [language, setLanguage] = useState<Language>("en"); useEffect(() => { const timer = window.setTimeout(() => { const saved = localStorage.getItem("vaayu-language") as Language | null; if (saved && copy[saved]) setLanguage(saved); }, 0); return () => window.clearTimeout(timer); }, []); const choose = (next: Language) => { setLanguage(next); localStorage.setItem("vaayu-language", next); }; return <I18n.Provider value={{ language, setLanguage: choose, t: copy[language] }}>{children}</I18n.Provider>; }
export const useCitizenI18n = () => useContext(I18n);
